---

- name: Create systemd services for node-exporter container
  ansible.builtin.template:
    src: templates/systemd.service.j2
    dest: "/etc/systemd/system/{{ node_exporter_container_service_name }}.service"
  register: service

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: service.changed

- name: Ensure node-exporter container is running
  ansible.builtin.service:
    name: "{{ node_exporter_container_service_name }}"
    state: started
    enabled: true
  retries: 3
