---
- name: Check if the service exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/{{ grafana_container_service_name }}.service"
  register: service_file

- when: service_file.stat.exists
  block:
  - name: Ensure service {{ grafana_container_service_name }} is stopped
    ansible.builtin.service:
      name: "{{ grafana_container_service_name }}"
      state: stopped

  - name: Remove systemd service for {{ grafana_container_name }} container
    ansible.builtin.file:
      dest: "/etc/systemd/system/{{ grafana_container_service_name }}.service"
      state: absent

  - name: Reload systemd
    ansible.builtin.systemd_service:
      daemon_reload: true

- name: Delete podman volume {{ grafana_data_volume_name }}
  containers.podman.podman_volume:
    name: "{{ grafana_data_volume_name }}"
    state: absent
  retries: 3
