---
- name: Install grafana container and systemd service
  hosts: grafana
  gather_facts: False
  become: True

  tasks:
  - name: Import grafana role
    ansible.builtin.import_role:
      name: grafana
      tasks_from: "{{ task | default('install') }}"
  
