---
- name: Create podman volumes
  containers.podman.podman_volume:
    state: present
    name: "{{ item }}"
  loop:
    - "{{ prometheus_config_volume_name }}"
    - "{{ prometheus_data_volume_name }}"

- name: Template prometheus.yml.j2 to host
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: "{{ podman_default_storage_path }}/{{ prometheus_config_volume_name }}/_data/prometheus.yml"
  register: prometheus_config

- name: Create systemd services for prometheus container
  ansible.builtin.template:
    src: templates/systemd.service.j2
    dest: "/etc/systemd/system/{{ prometheus_container_service_name }}.service"
  register: service

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: service.changed

- name: Restart prometheus if configuration changed
  ansible.builtin.service:
    name: "{{ prometheus_container_service_name }}"
    state: restarted
  when:
    - prometheus_config.changed
    - service.changed

- name: Ensure prometheus container is running
  ansible.builtin.service:
    name: "{{ prometheus_container_service_name }}"
    state: started
    enabled: true
  retries: 3
